[phases.setup]
nixPkgs = ['php82', 'composer', 'nodejs_20']

[phases.build]
cmds = [
    'npm install',
    'npm run build',
    'composer install --optimize-autoloader --no-dev',
    'php artisan config:cache',
    'php artisan route:cache',
    'php artisan view:cache'
]

[start]
cmd = 'chmod -R 777 storage bootstrap/cache && php artisan serve --host=0.0.0.0 --port=$PORT'
